#!/usr/bin/env php
<?php

require_once __DIR__.'/CartKernel.php';

use Symfony\Framework\WebBundle\Console\Application;

$kernel = new CartKernel('dev', true);

$application = new Application($kernel);
$application->run();
